[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Khai báo các thư viện cần thiết để PlatformIO tự động tải về
lib_deps =
  blynkkk/Blynk@^1.3.2
  bblanchon/ArduinoJson@^7.0.4