[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_port = COM5           ; Thay đổi nếu cổng COM của bạn khác

lib_deps =
    olikraus/U8g2 @ ^2.35.19 ; Thư viện màn hình OLED
    adafruit/DHT sensor library @ ^1.4.6 ; Thư viện cảm biến DHT
    adafruit/Adafruit Unified Sensor @ ^1.1.14