[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps = 
    khoih-prog/BlynkESP32_BT_WF@^1.2.2
    bblanchon/ArduinoJson@^7.2.2
    espressif/esp32-camera@^2.0.4

lib_ignore = ArduinoHttpClient