[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    beegee-tokyo/DHT sensor library for ESPx@^1.19
    mathworks/ThingSpeak@^2.0.0
