; ; PlatformIO Project Configuration File
; ; https://docs.platformio.org/page/projectconf.html

; [env:nodemcuv2]
; platform = espressif8266
; board = nodemcuv2
; framework = arduino

; ; Tốc độ Monitor để đọc Serial Debug
; monitor_speed = 115200

; ; Tốc độ nạp code (có thể tăng lên 921600 để nạp nhanh hơn)
; upload_speed = 115200

; lib_deps =
;     adafruit/DHT sensor library @ ^1.4.6
;     adafruit/Adafruit Unified Sensor @ ^1.1.14
;     olikraus/U8g2 @ ^2.35.19

; ; Các cài đặt bổ sung để build ổn định hơn
; build_flags = 
;     -D MQTT_MAX_PACKET_SIZE=512
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    olikraus/U8g2 @ ^2.35.19