[env:esp32dev]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps = 
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    https://github.com/avishorp/TM1637.git
    blynkkk/Blynk@^1.3.2
